import { Sparkles } from 'lucide-react';

/**
 * Prominent AI-written one-liner summarizing what owners say. Only rendered when
 * an AI headline exists (generated by the OpenRouter/Gemini provider).
 */
export function AiInsightCard({ headline }: { headline: string }) {
  return (
    <div className="relative overflow-hidden rounded-[var(--radius-2xl)] border border-accent/15 bg-accent-soft/60 p-5">
      <div
        className="pointer-events-none absolute -right-6 -top-6 h-24 w-24 rounded-full opacity-60"
        style={{ background: 'radial-gradient(circle, rgba(79,70,229,0.18), transparent 70%)' }}
        aria-hidden
      />
      <div className="relative flex gap-3">
        <div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-accent text-white shadow-[var(--shadow-glow)]">
          <Sparkles className="h-[1.05rem] w-[1.05rem]" strokeWidth={2.2} aria-hidden />
        </div>
        <div>
          <div className="text-[0.7rem] font-bold uppercase tracking-[0.08em] text-accent-ink/70">
            KI-Zusammenfassung
          </div>
          <p className="mt-1 text-[0.95rem] font-medium leading-relaxed text-ink">{headline}</p>
        </div>
      </div>
    </div>
  );
}
